### ISSUE TITLE
[Bug] Schedule text overflow

### ISSUE THREAD

**Issue by abdullah50053** [acmutd/hackportal#114]
### What did you expect to happen?

The text box should expand for longer text descriptions

### What happened?

Text overflow occurred in the description.

<img width="1439" alt="Screen Shot 2022-04-15 at 5 51 20 PM" src="https://user-images.githubusercontent.com/71054105/163650587-072d0d6f-1d76-4e7e-b431-1e8e0ecc3a9f.png">

### Scope

Events

**Comment by nam-t24** [comment]
This is still an issue? I thought I fixed it 😭

**Comment by nam-t24** [comment]
I think this might be from an outdated branch/deployment but the updated one should have y overflow scroll.

**Comment by abdullah50053** [comment]
The dev branch still has the overflow, check "Test Event" on April 1st

**Comment by nam-t24** [comment]
Oh I see the issue. The dev branch wasn't able to get the most recent updates because those merged pr's failed from Vercel limits.

**Comment by abdullah50053** [comment]
Redeploying
