### ISSUE TITLE
[Chore] Add App Header Profile Picture

### ISSUE THREAD

**Issue by nam-t24** [acmutd/hackportal#12]
# Overview

The user should be able to view their profile picture in the App Header to access their profile page.

# Proposal

* App Header Component
  * Top right corner should display rounded profile picture instead of 'profile' 

# Supplemental Information

* Conditional profile
  * App header displays rounded profile picture when user is signed in, 'sign-in' otherwise

**Comment by WillieCubed** [comment]
Could you push the branch and share the link to the preview deployment?

**Comment by nam-t24** [comment]
> Could you push the branch and share the link to the preview deployment?

I haven't started working on it since I'm trying to finish the rest of the dashboard sections. I wanted to open the feature to anyone since it isn't too high in priority on the calendar but would be nice to have completed.

**Comment by abdullah50053** [comment]
Resolved with sign-in / profile buttons.
