### ISSUE TITLE
[Feature] Allow for Notion page embeds in the HackerPack

### ISSUE THREAD

**Issue by abdullah50053** [acmutd/hackportal#149]
# Overview
The current HackerPack takes a while to set up and must be done by modifying the source code. Adding the ability to embed Notion pages will allow for increased customization and remove the need to go that deep into the source code.

# Proposal
Add the ability to embed Notion pages in the HackerPack

**Comment by MichaelZhao21** [comment]
It might not be smart to have Notion embeds as there's no official way to do it, and a lot of the solutions won't be anywhere as fast as a native HTML solution. Another issue with Notion embeds is that it would make the sidebar/menu extremely difficult or even impossible to implement.

I suggest we either have a JSON file that we read the data from or directly read from a markdown file. This would be much easier to edit, and Notion actually has the ability to export pages in the Markdown. 

We could also make a script to convert between Markdown and JSON, which would make it much easier for both the experience and dev teams. The workflow could be as simple as (1) export from Notion into Markdown, (2) update Markdown file in repo, (3) have the build script convert Markdown -> JSON -> HTML. We would just need to write a script (prob using a library) to read the Markdown file and generate a formatted JSON file. We could then easily map that JSON data to HTML and generate a static page.

**Comment by abdullah50053** [comment]
> It might not be smart to have Notion embeds as there's no official way to do it, and a lot of the solutions won't be anywhere as fast as a native HTML solution. Another issue with Notion embeds is that it would make the sidebar/menu extremely difficult or even impossible to implement.
> 
The idea behind it is to make it as easy for an organizer to configure as possible, so dropping the sidebar is fine if it means config is made easier. Agree that a native solution will be faster, and the portal is slow enough to load as is. 

> We could also make a script to convert between Markdown and JSON

We could definitely look into this. If all formatting and styling transfer over then I see no issue doing this. 
The biggest task with the hackerpack is to make it as easy to set up as possible, ideally without having to mess with the source code on the organizer side.
