### ISSUE TITLE
[Feature Request] Add Spotlight Section to Hack Center

### ISSUE THREAD

**Issue by abdullah50053** [acmutd/hackportal#15]
# Overview

The Spotlight section in Hack Center is a place where hackers can view events that are happening now if the hackathon is in progress. If the hackathon has not yet begun, random events that may interest the user will be shown.

# Proposal

The Spotlight section will have several key parts:
- A title, "Spotlight" by default,
- A description about the number of events happening at the time OR events the hacker may be interested in,
- A card displaying a quick summary of the event consisting of:
-The event title,
-The host(s),
-The date,
-The time,
-Location,
-And a link to the HackerPack
- The ability to scroll through cards

# Supplemental Information

<img width="631" alt="Screen Shot 2021-10-14 at 10 41 58 PM" src="https://user-images.githubusercontent.com/71054105/137428849-44d77656-2a5c-49dd-bf3e-97feb0c5515a.png">

Attached is an example of what the Spotlight section should look like. Scrolling through events will be done by pressing the arrows.

**Comment by nam-t24** [comment]
Done
