### ISSUE TITLE
[Fix] HackUTD IX Bugs

### ISSUE THREAD

**Issue by abdullah50053** [acmutd/hackportal#169]
# Overview

Several bugs are present in the current implementation that were changed in the HackUTD IX implementation:
- [x] Fix hacker can’t choose 0 hackathon experience
- [x] Fix notification request spam
- [x] First Name auto-fills Last Name
- [x] Remove default neon highlights around "Schedule" events
- [x] Remove “Sort by User Level” in the Admin dashboard

# Proposal

Fix the bugs

# Supplemental Information

See [HackUTD IX ](https://github.com/acmutd/hackutd-ix-site)site fork commits for fix

**Comment by NickBurnett** [comment]
Pretty sure hacker can choose 0 hackathon experience.

**Comment by spierceVR** [comment]
PR #163 Fixed a couple of these already
