### ISSUE TITLE
[Bug] Fix Spelling Error in Nav Dropdown

### ISSUE THREAD

**Issue by abdullah50053** [acmutd/hackportal#24]
# Overview

Dashboard and Schedule are spelled incorrectly

# Proposal

Fix the spelling

# Supplemental Information

<img width="122" alt="Screen Shot 2021-10-15 at 7 54 52 PM" src="https://user-images.githubusercontent.com/71054105/137567375-a77fde03-7a4d-450b-b61e-b67d801a73d0.png">

**Comment by fhdaax** [comment]
I think this issue is resolved. Isn't it?

**Comment by abdullah50053** [comment]
issue exists at `./components/AppHeader.tsx`

**Comment by fhdaax** [comment]
I am pretty sure there's no such issue in the mentioned file of the **develop** branch.

**Comment by WillieCubed** [comment]
Closing as this was resolved some time ago, but I have no idea which PR did it.
