### ISSUE TITLE
[Feature Request] Add HackerPack 

### ISSUE THREAD

**Issue by abdullah50053** [acmutd/hackportal#8]
# Overview
A HackPortal user should be able to view all information about the hackathon regarding workshop materials, events, food, etc. 

# Proposal
- Sidebar
	- General
	- Workshop Type(sponsor, tech, comm)
		- name of workshops
	- Hacker name and welcome at the bottom
- Dashboard
	- Hack Center
	- Scan-in
	- HackerPack
	- Project submission
- Main Content
	- Document links
	- Header and info

HackerPack must include the following:
Sidebar, dashboard, navigation bar

This application will exist at the route `/dashboard/hackerpack` and exist as a dynamic page. A hacker must be able to view and go to each subsection of the page via the sidebar menu. A sponsor should be able to view the workshop materials that are required for their own workshop. The dashboard should be accessible at all times to access other sections of the dashboard.

**Comment by nam-t24** [comment]
Hackerpack is finished. Next step is to add ability to fetch main content from outside documents to display in the hacker pack section, instead of directly writing out content into code.
